service: reading-list

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:667395001029:table/Books"

functions:
  create:
    handler: books/create.create
    events:
      - http:
          path: books
          method: post
          cors: true
          authorizer: aws_iam
  list:
    handler: books/list.list
    events:
      - http:
          path: books
          method: get
          cors: true
          authorizer: aws_iam
  get:
    handler: books/get.get
    events:
      - http:
          path: books/{id}
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: books/update.update
    events:
      - http:
          path: books/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: books/delete.delete
    events:
      - http:
          path: books/{id}
          method: delete
          cors: true
          authorizer: aws_iam	  

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Books
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: Id
            AttributeType: S	    	    
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE	    
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
